openapi: 3.0.0

# Metadata about the API
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"  # Base path for the API, all endpoints will be prefixed with /api, e.g. https://example.com/api/people

# Components are reusable parts of the API specification
components:
  # Definition of reusable schemas (data models)
  schemas:
    # Definition of the Person object schema (data model)
    Person:
      type: "object"
      required:  # List of required properties for the Person object; must exist in "properties"
        - lname
      properties:  # Properties of the Person object
        fname:  # "First Name" property of Person
          type: "string"
        lname:  # "Last Name" property of Person
          type: "string"
  # Definition of reusable parameters for endpoints
  parameters:
    lname:
      name: "lname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"
    note_id:
      name: "note_id"
      description: "ID of the note"
      in: path
      required: true
      schema:
        type: "integer"

paths:
  /people:
    # Get to list all people
    get:
      operationId: "people.read_all"  # Python function to handle this endpoint
      tags:  # Categorization tag for the endpoint; allows grouping in documentation
        - "People"
      summary: "Read the list of people"  # UI summary for the endpoint
      responses:  # Status codes and their descriptions for the endpoint
        "200":
          description: "Successfully read people list"
    # Post to create a new person
    post:
      operationId: "people.create"
      tags:
        - People
      summary: "Create a person"
      requestBody:  # Block requestBody defines the body of the request for POST/PUT endpoints
          description: "Person to create"
          required: True
          x-body-name: "person"  # Name of the body parameter changed from "body" to "person"
          content:
            application/json:  # Content type of the request body; data exchange format
              schema:  # Schema of the request body
                $ref: "#/components/schemas/Person"  # Reference to the Person schema defined in components
      responses:
        "201":
          description: "Successfully created person"
  /people/{lname}:
    get:
      operationId: "people.read_one"
      tags:
        - People
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully read person"
        "404":
          description: "Person not found"
    put:
      tags:
        - People
      operationId: "people.update"
      summary: "Update a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully updated person"
        "404":
          description: "Person not found"
      requestBody:
        x-body-name: "person"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
    delete:
      tags:
        - People
      operationId: "people.delete"
      summary: "Delete a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Successfully deleted person"
        "404":
          description: "Person not found"
  /notes:
    post:
      operationId: "notes.create"
      tags:
        - Notes
      summary: "Create a note associated with a person"
      requestBody:
          description: "Note to create"
          required: True
          x-body-name: "note"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  person_id:
                    type: "integer"
                  content:
                    type: "string"
      responses:
        "201":
          description: "Successfully created a note"
  /notes/{note_id}:
    get:
      operationId: "notes.read_one"
      tags:
        - Notes
      summary: "Read one note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "200":
          description: "Successfully read one note"
        "404":
          description: "Note not found"
    put:
      tags:
        - Notes
      operationId: "notes.update"
      summary: "Update a note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "200":
          description: "Successfully updated note"
        "404":
          description: "Note not found"
      requestBody:
        x-body-name: "note"
        content:
          application/json:
            schema:
              type: "object"
              properties:
                content:
                  type: "string"
    delete:
      tags:
        - Notes
      operationId: "notes.delete"
      summary: "Delete a note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "204":
          description: "Successfully deleted note"
        "404":
          description: "Note not found"